import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { X, ExternalLink, Clock, MapPin, Bell, Share2, MessageSquareShare, Download } from 'lucide-react'
import SeverityBadge from '../ui/SeverityBadge'
import { useIncidentStore } from '../../store/useIncidentStore'

function timeAgo(date) {
  const diff = Date.now() - new Date(date).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return 'Just now'
  if (mins < 60) return `${mins} min ago`
  return `${Math.floor(mins / 60)}h ago`
}

export default function DetailPanel({ incidentId, onClose }) {
  const { activeIncident, fetchIncident } = useIncidentStore()

  useEffect(() => {
    if (incidentId) fetchIncident(incidentId)
  }, [incidentId])

  if (!activeIncident) return null

  const inc = activeIncident

  return (
    <div className="absolute right-0 top-0 bottom-0 w-[380px] bg-deep-slate border-l border-white/[0.08] z-20 animate-slide-in overflow-y-auto">
      <div className="sticky top-0 bg-deep-slate border-b border-white/[0.08] p-4 flex items-center justify-between">
        <SeverityBadge severity={inc.severity} />
        <button onClick={onClose} className="p-1 rounded-md text-cool-gray hover:text-glacier-white hover:bg-white/5">
          <X size={18} />
        </button>
      </div>

      <div className="p-4 space-y-4">
        <div>
          <h2 className="text-lg font-bold text-glacier-white capitalize">{inc.event_type.replace('_', ' ')}</h2>
          {inc.subtype && <p className="text-sm text-cool-gray">{inc.subtype}</p>}
          <div className="flex items-center gap-1.5 text-sm text-glacier-white mt-1">
            <MapPin size={14} className="text-cool-gray" />
            <span>{inc.location.name}</span>
          </div>
          <div className="text-[11px] font-mono text-cool-gray/60 mt-0.5">
            {inc.location.lat?.toFixed(4)}, {inc.location.lng?.toFixed(4)}
          </div>
        </div>

        <div className="flex items-center gap-2 text-xs text-cool-gray/60">
          <Clock size={12} />
          <span>Updated {timeAgo(inc.last_updated)}</span>
          {inc.ai_confidence && (
            <span className="ml-auto text-ai-purple">AI: {Math.round(inc.ai_confidence * 100)}%</span>
          )}
        </div>

        <div className="bg-[#1a1040] border border-ai-purple/30 rounded-lg p-4 border-l-4 border-l-ai-purple">
          <div className="flex items-center gap-1.5 mb-2">
            <div className="text-[10px] font-semibold text-ai-purple bg-ai-purple/20 px-2 py-0.5 rounded">AI GENERATED</div>
          </div>
          <p className="text-sm text-glacier-white leading-relaxed">{inc.summary}</p>
          <p className="text-[11px] text-cool-gray/60 mt-2">Generated by Claude AI from {inc.source_count} sources</p>
        </div>

        {inc.stats && (
          <div className="grid grid-cols-2 gap-2">
            {inc.stats.magnitude && (
              <div className="bg-surface rounded-lg p-3 border border-white/[0.06]">
                <div className="text-[11px] text-cool-gray">Magnitude</div>
                <div className="text-lg font-bold text-glacier-white">{inc.stats.magnitude}</div>
              </div>
            )}
            {inc.stats.deaths != null && (
              <div className="bg-surface rounded-lg p-3 border border-white/[0.06]">
                <div className="text-[11px] text-cool-gray">Deaths</div>
                <div className="text-lg font-bold text-crisis-red">{inc.stats.deaths.toLocaleString()}</div>
              </div>
            )}
            {inc.stats.displaced != null && (
              <div className="bg-surface rounded-lg p-3 border border-white/[0.06]">
                <div className="text-[11px] text-cool-gray">Displaced</div>
                <div className="text-lg font-bold text-amber">{inc.stats.displaced.toLocaleString()}</div>
              </div>
            )}
            {inc.stats.wind_speed && (
              <div className="bg-surface rounded-lg p-3 border border-white/[0.06]">
                <div className="text-[11px] text-cool-gray">Wind Speed</div>
                <div className="text-lg font-bold text-signal-blue">{inc.stats.wind_speed} km/h</div>
              </div>
            )}
          </div>
        )}

        <div className="flex flex-wrap gap-2">
          <Link to={`/incident/${inc._id}`}
            className="flex items-center gap-1.5 bg-surface border border-white/10 rounded-lg px-3 py-2 text-sm text-glacier-white hover:border-white/30 transition-colors">
            <ExternalLink size={14} />
            Full Details
          </Link>
          <button className="flex items-center gap-1.5 bg-status-teal/20 text-status-teal border border-status-teal/30 rounded-lg px-3 py-2 text-sm hover:bg-status-teal/30 transition-colors">
            <Bell size={14} />
            Alert me
          </button>
          <button className="flex items-center gap-1.5 bg-surface border border-white/10 rounded-lg px-3 py-2 text-sm text-cool-gray hover:text-glacier-white transition-colors">
            <Share2 size={14} />
            Share
          </button>
        </div>
      </div>
    </div>
  )
}
